headless: false  # Set to true for VPS, false for local with display
timezone: "Europe/Amsterdam"

# Posting mode: "rotation" or "sequential"
# rotation: One post per model, then cycle back (Nathalya1 → Lunaa1 → Laura1 → Naomi1 → Nathalya2...)
# sequential: Complete all posts for each model before next (Nathalya1-9 → Lunaa1-8 → Laura1-8 → Naomi1-10)
posting_mode: "rotation"

timeouts:
  default_ms: 15000
  long_ms: 30000

retries:
  clicks: 3
  scroll_attempts: 8
  scroll_pause_ms: 600

pace:
  between_posts:
    mode: "fixed"              # For sequential mode: delay between posts of same model
    fixed_seconds: 60
  between_models: 1200          # Delay between models (rotation) or between model switches (sequential)
  cycle_delay: 1200             # Optional: delay between full cycles in rotation mode

cookies_path: "./cookies.json"

caption_archive:
  type: "json"
  json_path: "./captions/used_global.json"
  replenish_when_empty: true
  after_replenish_clear_archive: false

# State tracking file
state_file: "./posting_state.json"

models:
  - name: "Nathalya"
    total_posts: 9
    pattern: ["free", "free", "fans", "free", "free", "fans", "free", "free", "fans"]
    folders: {
      "free": "Lingerie Foto's",
      "fans": "Lingerie Video's"
    }
    nested_folders: {
      "parent": "software"  # Click this folder first, then the specific folder
    }
    media: {
      "free": { count: 1, type: "photo" },
      "fans": { count: 1, type: "video" }
    }
    caption:
      enabled: true
      excel:
        path: "./captions.xlsx"
        sheet: "Blad1"
        column: "A"
        pick_strategy: "sequential"
      hashtags:
        enabled: true
        list: ["#nathalya", "#nathalyadriesen", "#lesbian", "#blowjob", "#doggy", "#girlnextdoor", "#normalgirl", "#normalemeid", "#naturealboobs", "#stoutemeid", "#sexyogen", "#kont", "#sexvideos", "#dutch", "#naughty", "#tightpussy", "#amateur", "#wetpussy", "#tattoo", "#sexy"]

  - name: "Lunaa"
    total_posts: 8
    pattern: ["free", "free", "free", "free", "free", "free", "free", "free"]
    folders: {
      "free": "Lingerie Foto's"
    }
    nested_folders: {
      "parent": "software"
    }
    media: {
      "free": { count: 1, type: "photo" }
    }
    caption:
      enabled: true
      excel:
        path: "./captions.xlsx"
        sheet: "Blad1"
        column: "A"
        pick_strategy: "sequential"
      hashtags:
        enabled: true
        list: ["#girlnextdoor", "#gymgirl", "#model", "#stoutemeid", "#naughty", "#blondie", "#barbie", "#boobs"]

  - name: "Lauraclauw"
    total_posts: 8
    pattern: ["free", "free", "free", "free", "free", "free", "free", "free"]
    folders: {
      "free": "Lingerie Foto's"
    }
    nested_folders: {
      "parent": "software"
    }
    media: {
      "free": { count: 1, type: "photo" }
    }
    caption:
      enabled: true
      excel:
        path: "./captions.xlsx"
        sheet: "Blad1"
        column: "A"
        pick_strategy: "sequential"
      hashtags:
        enabled: true
        list: ["#blonde", "#barbie", "#lauraclauw", "#girlnextdoor", "#lingerie", "#stoutemeid", "#dutch", "#mdemma", "#megan"]

  - name: "Naomivanstraatten"
    total_posts: 10
    pattern: ["free", "free", "fans", "free", "free", "fans", "free", "free", "fans", "free"]
    folders: {
      "free": "Lingerie Foto's",
      "fans": "Lingerie Foto's"
    }
    nested_folders: {
      "parent": "software"
    }
    media: {
      "free": { count: 1, type: "photo" },
      "fans": { count: 1, type: "video" }
    }
    caption:
      enabled: true
      excel:
        path: "./captions.xlsx"
        sheet: "Blad1"
        column: "A"
        pick_strategy: "sequential"
      hashtags:
        enabled: true
        list: ["#porn", "#milf", "#cougar", "#nude", "#mommy", "#buurvrouw"]