headless: false
timezone: "Europe/Amsterdam"   # used for schedule.at parsing

timeouts:
  default_ms: 15000
  long_ms: 30000

retries:
  clicks: 3
  scroll_attempts: 8
  scroll_pause_ms: 600

pace:
  between_posts:
    mode: "fixed"              # fixed | random | none
    fixed_seconds: 5           # reduced for testing
  between_models:
    mode: "fixed"
    fixed_seconds: 10          # reduced for testing

cookies_path: "./cookies.json"

caption_archive:
  type: "json"                           # "json" | "excel"
  json_path: "./captions/used_global.json"
  excel:
    path: "./captions/used_global.xlsx"
    sheet: "Used"
    column: "A"
  replenish_when_empty: true
  after_replenish_clear_archive: false   # only for json

models:
  - name: "Amalia.a"

    caption:
      enabled: true
      excel:
        path: "./captions.xlsx"
        sheet: "Sheet1"
        column: "A"
        pick_strategy: "sequential"      # sequential | random
      hashtags:
        enabled: true
        list: ["#daily", "#exclusive", "#f2f"]

    posts:
      - name: "test_paid_post"
        folder_filter: { name_contains: "lingerie foto" }
        media: { count: 2, type: "photo" }
        post_type: "paid"
        paid:
          variant: "non_fans_pay"
          prices: { followers: 9.99 }

